package com.eaton.platform.core.constants;

public final class AssetDownloadConstants {

    private AssetDownloadConstants() {}

    public static final String PARAMETER_KEY_DOWNLOAD_FILE_NAME = "downloadFileName";
    public static final String PARAMETER_KEY_DOWNLOAD_ASSET_PATHS = "downloadAssetPaths";
    public static final String PARAMETER_KEY_EMAIL_TO_RECIPIENTS = "emailToRecipients";
    public static final String PARAMETER_KEY_RESOURCE_PATH = "resourcePath";
    public static final String PARAMETER_KEY_EMAIL_CONFIG = "emailConfig";
    public static final String PARAMETER_KEY_DOWNLOAD_PACKAGE_IDENTIFIER = "downloadPackageIdentifier";
    public static final String PARAMETER_KEY_EMAIL_LINK_PATH = "emailLinkPath";
    public static final String PARAMETER_KEY_DOWNLOAD_PACKAGE_ID = "etnPackId";
    public static final String PARAMETER_KEY_MERGE_ASSETS_TO_SINGLE_PDF = "mergeAssetsToSinglePDF";
    public static final String PARAMETER_KEY_MERGE_ASSETS_FILE_NAME = "mergeAssetsFileName";
    public static final String PDF_EXTN_WTIH_DOT = ".pdf";
    public static final String MERGE_ASSETS_FILE_NAME_DEFAULT_VALUE = "Eaton Submittal Builder Package".concat(PDF_EXTN_WTIH_DOT);
    public static final String EMAIL_DOWNLOAD_ASSET_PACKAGE_WF_MODEL_ID = "/var/workflow/models/eaton-workflows/eaton-asset-download";
    public static final String DOWNLOAD_FILE_NAME_DEFAULT_VALUE = "AssetPackage";
    public static final String SENDER_EMAIL_ADDRESS = "senderEmailAddress";
    public static final String SENDER_NAME = "senderName";
    public static final String SUBJECT = "subject";
    public static final String MAIL_LINK = "mailLink";
    public static final String EMAIL_TEMPLATE = "emailTemplate";
    public static final String JSON = ".json";
    public static final String DOT = ".";
    public static final String APPLICATION_JSON = "application/json";
    public static final String ASSET_DOWNLOAD_MAIL_CONFIG_PATH = "assetDownloadPackageMailConfigPath";
    public static final String JCR_PATH = "JCR_PATH";
    public static final String ERROR_MESSAGE_UNIQUE_ID_MISSING = "Request parameter etnPackId not passed";
    public static final String STATUS = "status";
    public static final String FAIL = "fail";
    public static final String MESSAGE = "message";
    public static final String ERROR_CODE = "errorcode";
    public static final String EMAIL_SENDER_NAME = "emailSenderName";
    public static final String EMAIL_SUBJECT = "emailSubject";
    public static final String EMAIL_SENDER_ADDRESS = "emailSenderAddress";
    public static final String QUESTION_MARK = "?";
    public static final String EQUALS = "=";
    public static final String RESOURCE_NOT_FOUND = "Resource not found exception";
    public static final String LOCATION = "Location";
    public static final String CONNECTION = "Connection";
    public static final String CLOSE = "close";
    public static final String SUBMITTAL_DOWNLOAD = "submittaldownload";
    public static final String EMAIL_NEWS_LETTER_LINK = "emailNewsLetterLink";
    public static final String EMAIL_SUBMITTAL_TOOL_LINK = "emailSubmittalBuilderToolLink";
    public static final String EMAIL_CONTACT_US_LINK = "emailContactUsLink";
    public static final String EMAIL_WHERE_TO_BUY_LINK = "emailWhereToBuyLink";
    public static final String DOWNLOAD = "download";
    public static final String EMAIL = "email";
    public static final String SUBMITTAL_BUILDER_DOWNLOAD = "submittalbuilderdownload";
    public static final String ZIP_CONTENT_TYPE = "application/zip";
    public static final String CONTENT_DISPOSITION_KEY = "Content-Disposition";
    public static final String CONTENT_DISPOSITION_VALUE = "attachment; filename=\"%s.zip\"";
    public static final String FILE_NAME = "fileName";
    public static final String ASSET_PATHS = "assetPaths";
    public static final String EMAIL_TO_RECIPIENTS = "emailToRecipients";
    public static final String UNIQUE_ID = "UNIQUEID";
    public static final String WORKFLOW_ERROR = "WORKFLOWERROR";
    public static final String EMAIL_LINK_PATH_SELECTOR = DOT.concat(SUBMITTAL_BUILDER_DOWNLOAD).concat(JSON);
    public static final String SUBMITTAL_BUILDER_EMAIL_SELECTOR = DOT.concat(SUBMITTAL_BUILDER_DOWNLOAD).concat(".email").concat(JSON);
    public static final String SUBMITTAL_BUILDER_DOWNLOAD_SELECTOR = DOT.concat(SUBMITTAL_BUILDER_DOWNLOAD).concat(".download").concat(JSON);
    public static final String SUBMITTAL_BUILDER_RESULTS_SELECTOR = ".submittalbuilderresults.json";
    public static final String SELECTOR_ERROR = "SELECTORERROR";
    public static final String ERROR_INVALID_SELECTOR_PASSED = "Error invalid selector passed";
    public static final String ERROR_SENDING_EMAIL = "Error while sending email";
    public static final String EMAIL_ERROR = "EMAILERROR";
    public static final String ERROR_STARTING_WORKFLOW = "Error starting workflow";
    public static final String ERROR_INVALID_REQUEST_PARAMETERS = "Error invalid request parameters";
    public static final String INVALID_REQUEST_ERROR = "INAVLIDREQUESTERROR";
    public static final String SCOPE = "scope";
    public static final String FACETS = "facets";
    public static final String SORT_ORDER = "sortOrder";
    public static final String ACTIVE_FILTERS = "activeFilters";
    public static final String STARTING_RECORD = "startingRecord";
    public static final String[] REQUIRED_PARAMS = {SCOPE, FACETS, SORT_ORDER, ACTIVE_FILTERS};
    public static final String SUBMITTAL_BUILDER_RESOURCE_PATH = "eaton/components/content/submittalbuilder";
    public static final String ENDECA_ERROR_RESPONSE = "{ \"error\": \"Error generating response.\" }";
    public static final String DOCUMENT_LINKS = "documentLinks";
}
