/**
 *
 *
 *
 * - THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY -
 * - Generated by Gulp (gulp-babel).
 *
 *
 *
 *
 */


'use strict';

$(document).ready(function () {
  $('#agent').prop('selectedIndex', 0);
  $('#agent').on('change', function () {
    var divisionIds = $(this).val();
    var items = divisionIds.split(',');
    $('#division').empty();
    var selectYourDivisionText = $('.agent-report-division').attr('data-select-your-division-label');
    $('#division').append('<option value="selectYourDivision">' + selectYourDivisionText + '</option>');
    $.each(items, function (key, value) {
      var vSplit = value.split(':');
      if (vSplit[1] !== undefined) {
        $('#division').append('<option value="' + vSplit[0] + '">' + vSplit[1] + '</option>');
      }
    });
    $('#reports').prop('disabled', true);
    $('.fileDownload').empty();
    $('#reports-data').hide();
    $('#no-rows-alert').hide();
    $('.agent-loader').show();
  });

  $('#reports').click(function (e) {
    e.preventDefault();

    $.ajax({
      type: 'POST',
      url: '/eaton/agentreports/getReports',
      data: {
        agentId: $('#agent option:selected').html(),
        division: $('#division').val()
      },
      success: function success(result) {
        $('.agent-loader').show();
        if (!$.trim(result)) {
          $('#no-rows-alert').show();
        } else {
          $('#no-rows-alert').hide();
          var html = void 0;
          $.each(result, function (index, value) {
            html += '<tr>' + '<td class="data-td"> <a id="' + value.DDocName + '" data-value="' + value.DDocName + '">' + value.DOriginalName + '</a></td>' + '<td>' + value.DInDate + '</td>' + '</tr>';
          });

          $('.table-striped tbody').html(html);
        }
        $('.agent-loader').hide();
      }

    });
    $('#reports-data').show();
  });

  $('.fileDownload').click(function (e) {
    e.preventDefault();
    var docName = e.target.id;
    var fileName = $(event.target).text();
    $.ajax({
      type: 'POST',
      url: '/eaton/agentreports/getFileDownload',
      data: {
        docName: docName
      },
      xhrFields: {
        responseType: 'blob'
      },
      success: function success(result) {
        var blob = new Blob([result]);
        var link = document.createElement('a');
        link.href = window.URL.createObjectURL(blob);
        link.download = fileName;
        link.click();
      }
    });
  });
  $('#division').on('change', function () {
    if ($(this).val() === 'selectYourDivision') {
      $('#reports').prop('disabled', true);
    } else {
      $('#reports').prop('disabled', false);
    }
    $('.fileDownload').empty();
    $('#reports-data').hide();
    $('#no-rows-alert').hide();
    $('.agent-loader').show();
  });

  function sortTable(f, n) {
    var rows = $('#agent-table tbody  tr').get();

    rows.sort(function (a, b) {

      var A = getVal(a);
      var B = getVal(b);

      if (A < B) {
        return -1 * f;
      }
      if (A > B) {
        return 1 * f;
      }
      return 0;
    });

    function getVal(elm) {
      var v = $(elm).children('td').eq(n).text().toUpperCase();
      if ($.isNumeric(v)) {
        v = parseInt(v, 10);
      }
      return v;
    }

    $.each(rows, function (index, row) {
      $('#agent-table').children('tbody').append(row);
    });
  }
  /* eslint-disable */
  var f_sl = 1;
  var f_nm = 1;
  $('#sl').click(function () {
    f_sl *= -1;
    var n = $(this).prevAll().length;
    sortTable(f_sl, n);
  });
  $('#nm').click(function () {
    f_nm *= -1;
    var n = $(this).prevAll().length;
    sortTable(f_nm, n);
  });
  /* eslint-disable */
});