package com.eaton.platform.integration.endeca.pojo.base;

/**
 * Enum for all the different endeca fields
 */
public enum EndecaFieldEnum {
    SECURE, TITLE, PUBLISH_DATE, URL, FILE_SIZE, CONTENT_TYPE, STATUS, EPOCHPUBDATE, FILE_TYPE, DESCRIPTION,
    IMAGE, TRACKDOWNLOAD, LANGUAGE, COUNTRY, INVENTORY_ID, MKTG_DESC, GLOBAL_ATTRS, TAXONOMY_ATTRS, IMAGES, DOCUMENTS,
    UPSELL, CROSSSELL, REPLACEMENT, CID, CATALOG_NUMBER, EXTENSION_ID, BRAND, SUBBRAND, TRADE_NAME, FAMILY_NAME, DC_FORMAT
}
