/**
 *
 *
 *
 * - THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY -
 * - Generated by Gulp (gulp-babel).
 *
 *
 *
 *
 */


//-----------------------------------
// Resources List
//-----------------------------------
'use strict';

var App = window.App || {};
App.resourceList = function () {

  var $accordion = $('.panel-group');
  var $component = $('.secondary-content-accordion');
  var $link = $('[data-scroll-to]');

  var init = function init() {
    $accordion.on('hidden.bs.collapse', toggleIcon);
    $accordion.on('shown.bs.collapse', toggleIcon);
    $accordion.on('hidden.bs.collapse', toggleIconQR);
    $accordion.on('shown.bs.collapse', toggleIconQR);
    $link.on('click', expand);
  };

  var resourceDownloadAll = $('.resource_download_all');
  if (resourceDownloadAll.length > 0) {
    $('.disclaimer').show();
  }

  resourceDownloadAll.click(function () {
    var category = $(this).attr('data-category-name');
    var productName = $(this).attr('data-product-family');
    var categoryId = location.pathname.split('.')[1];
    var zipFileName = category.concat('-').concat(productName).concat('-').concat(categoryId).concat('.zip');
    zipFileName = zipFileName.replace(/\s/g, '-');
    var requestParams = {
      documentLinks: JSON.parse(this.dataset.resourceLinks)
    };
    var loader = $('.loader');

    loader.addClass('loader-active');

    $.ajax({
      type: 'POST',
      url: '/eaton/content/assetzipdownload.zip',
      data: JSON.stringify(requestParams),
      headers: { 'Content-Type': 'application/zip' },
      success: function success(resultData) {
        loader.removeClass('loader-active');

        if (resultData) {
          var byteCharacters = atob(resultData);
          var byteNumbers = new Array(byteCharacters.length);
          for (var i = 0; i < byteCharacters.length; i++) {
            byteNumbers[i] = byteCharacters.charCodeAt(i);
          }
          var byteArray = new Uint8Array(byteNumbers);
          var blob = void 0;
          var fileType = 'application/zip';
          var fileNameExt = zipFileName;
          if (window.navigator.msSaveBlob) {
            blob = new Blob([byteArray], { type: fileType });
            window.navigator.msSaveBlob(blob, fileNameExt);
          } else {
            var _blob = new Blob([byteArray], { type: fileType });
            var link = document.createElement('a');
            link.href = window.URL.createObjectURL(_blob);
            link.download = fileNameExt;
            document.body.appendChild(link);
            link.click();
            document.body.removeChild(link);
          }
        }
      },
      error: function error() {
        loader.removeClass('loader-active');
      }
    });
  });

  /**
   * Toggle class icon
   */
  var toggleIcon = function toggleIcon(event) {

    $(event.target).prev('.panel-heading').find('.icon').toggleClass('icon-sign-plus icon-sign-minus');
  };
  var toggleIconQR = function toggleIconQR(event) {

    $(event.target).prev('.panel').find('.icon').toggleClass('icon-sign-plus icon-sign-minus');
  };

  /**
   * Expand accordion when link is clicked
   */
  var expand = function expand(event) {

    var idHeading = $(event.target).closest('.module-anchor-links__list-link').attr('data-scroll-to');
    $accordion.find($(idHeading)).next().collapse('show');
  };

  /**
   * Initialize and Expose public methods
   */

  if ($component.length > 0) {
    init();
  }
};

/**
 * jQuery for custom resource list design.
 */

$(document).ready(function () {
  App.resourceList();
  var customResourcePopup = $('.custom-resource-popup ');
  $('.popup-content').on('click', function () {
    var a = $(this).closest('li');
    var bigImage = $(a).attr('data-rendition-big-image') || $(a).attr('data-rendition-319x319');
    var getSecureIcon = $(a).find('.resource-list__secure-icon').html() || '';
    $('.custom-resource-popup .resource-big-image').attr('src', bigImage);
    $('.custom-resource-popup .resource-big-title').html($(this).attr('data-title'));
    $('.custom-resource-popup .resource-big-description').html($(this).attr('data-desc'));
    $('.custom-resource-popup .resource-big-secure').html(getSecureIcon);
    $('.custom-resource-popup .resource-big-downloadlink').attr('href', bigImage);
    $('.custom-resource-popup .resource-big-div').css('background-image', 'url(' + bigImage + ')');
    customResourcePopup.removeClass('hide');
    customResourcePopup.addClass('show');
  });

  $('.resource-big-close').on('click', function () {
    $('.custom-resource-popup .resource-big-image').attr('src', '');
    $('.custom-resource-popup .resource-big-title').html('');
    $('.custom-resource-popup .resource-big-description').html('');
    $('.custom-resource-popup .resource-big-downloadlink').attr('href', '#');
    $('.custom-resource-popup .resource-big-secure').html('');
    $('.custom-resource-popup .resource-big-div').css('background-image', 'url("")');
    customResourcePopup.removeClass('show');
    customResourcePopup.addClass('hide');
  });

  var resourceListContainer = document.getElementsByClassName('resource-list');
  if (resourceListContainer.length > 0) {
    var bulkDownloadContainer = document.getElementsByClassName('bde-activated');
    if (bulkDownloadContainer.length > 0) {
      bulkDownloadContainer[0].dispatchEvent(new CustomEvent('responseRendered'));
    }
    $(document).on('click', 'input[name=toDownload]', function () {

      var checkedInputs = document.querySelectorAll('input[name=toDownload]:checked');
      var tempCount = checkedInputs.length;
      var actualLimitSet = parseInt($('#selected-files-drawer-box').attr('data-download-file-count-limit'));
      // For size limit, check this condition: "checkSize > maxZipLimit" instaed of 'actualLimitSet < tempCount' in folloing if.
      if (actualLimitSet < tempCount) {
        return false;
      }
      var allSelectedFiles = [];
      $(checkedInputs).each(function () {
        if (!$(this).hasClass('disabledbutton')) {
          // check id and if matched pushed it to selected queue.
          allSelectedFiles.push({
            id: $(this).attr('id'),
            title: $(this).attr('title'),
            url: $(this).attr('data-url')
          });
        }
      });
      sessionStorage.setItem('selectedFiles', JSON.stringify(allSelectedFiles));

      // Check and set the counter
      var selectionCount = 0;
      $(checkedInputs).each(function () {
        if (!$(this).hasClass('disabledbutton')) {
          selectionCount++;
        }
      });
      if (selectionCount === 0) {
        $('#bulkDownloadContainer').addClass('disabledbutton');
        $('#selecteddownload').html('(0)');
      } else {
        $('#bulkDownloadContainer').removeClass('disabledbutton');
        $('#selecteddownload').html('(' + selectionCount + ')');
      }
      // Function to add element in drawer for bulk download.funtion defination in asset-bulk-download-email.js
      /* eslint-disable no-undef */
      addRemovefileForBDE();
    });
  }
});