//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.04.22 at 02:31:15 PM EDT
//


package com.eaton.platform.core.models;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;

/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ATR_GRP" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="ATR_NM" maxOccurs="unbounded" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;simpleContent&gt;
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                           &lt;attribute name="Label" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                           &lt;attribute name="SEQ" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
 *                           &lt;attribute name="STNDR" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                           &lt;attribute name="Value" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                           &lt;attribute name="CID" type="{http://www.w3.org/2001/XMLSchema}long" /&gt;
 *                           &lt;attribute name="UOM" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                           &lt;attribute name="Display_Flag" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                           &lt;attribute name="Language" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                           &lt;attribute name="Country" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                           &lt;attribute name="REPFL" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                           &lt;attribute name="LOVSQ" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                         &lt;/extension&gt;
 *                       &lt;/simpleContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="ATR_MULTI_ROW" maxOccurs="unbounded" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="ATR_NM" maxOccurs="unbounded" minOccurs="0"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;simpleContent&gt;
 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                                     &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                     &lt;attribute name="Label" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                     &lt;attribute name="SEQ" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
 *                                     &lt;attribute name="Value" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                     &lt;attribute name="STNDR" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                     &lt;attribute name="REPFL" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                     &lt;attribute name="LOVSQ" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                     &lt;attribute name="UOM" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                   &lt;/extension&gt;
 *                                 &lt;/simpleContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                           &lt;attribute name="SEQ" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
 *                           &lt;attribute name="ROWID" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="Label" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="SEQ" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
 *                 &lt;attribute name="SUBTYPE" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="Label" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="SEQ" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "atrgrp"
})
@XmlRootElement(name = "ATR_GRP_TYPE")
public class ATRGRPTYPE {

    @XmlElement(name = "ATR_GRP")
    protected List<ATRGRPTYPE.ATRGRP> atrgrp;
    @XmlAttribute(name = "id")
    protected String id;
    @XmlAttribute(name = "Label")
    protected String label;
    @XmlAttribute(name = "SEQ")
    protected Short seq;

    /**
     * Gets the value of the atrgrp property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the atrgrp property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getATRGRP().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ATRGRPTYPE.ATRGRP }
     *
     *
     */
    public List<ATRGRPTYPE.ATRGRP> getATRGRP() {
        if (atrgrp == null) {
            atrgrp = new ArrayList<ATRGRPTYPE.ATRGRP>();
        }
        return this.atrgrp;
    }

    /**
     * Gets the value of the id property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the label property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setLabel(String value) {
        this.label = value;
    }

    /**
     * Gets the value of the seq property.
     *
     * @return
     *     possible object is
     *     {@link Short }
     *
     */
    public Short getSEQ() {
        return seq;
    }

    /**
     * Sets the value of the seq property.
     *
     * @param value
     *     allowed object is
     *     {@link Short }
     *
     */
    public void setSEQ(Short value) {
        this.seq = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="ATR_NM" maxOccurs="unbounded" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;simpleContent&gt;
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
     *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                 &lt;attribute name="Label" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                 &lt;attribute name="SEQ" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
     *                 &lt;attribute name="STNDR" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                 &lt;attribute name="Value" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                 &lt;attribute name="CID" type="{http://www.w3.org/2001/XMLSchema}long" /&gt;
     *                 &lt;attribute name="UOM" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                 &lt;attribute name="Display_Flag" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                 &lt;attribute name="Language" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                 &lt;attribute name="Country" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                 &lt;attribute name="REPFL" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                 &lt;attribute name="LOVSQ" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *               &lt;/extension&gt;
     *             &lt;/simpleContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="ATR_MULTI_ROW" maxOccurs="unbounded" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="ATR_NM" maxOccurs="unbounded" minOccurs="0"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;simpleContent&gt;
     *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
     *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                           &lt;attribute name="Label" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                           &lt;attribute name="SEQ" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
     *                           &lt;attribute name="Value" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                           &lt;attribute name="STNDR" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                           &lt;attribute name="REPFL" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                           &lt;attribute name="LOVSQ" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                           &lt;attribute name="UOM" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                         &lt;/extension&gt;
     *                       &lt;/simpleContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/sequence&gt;
     *                 &lt;attribute name="SEQ" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
     *                 &lt;attribute name="ROWID" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="Label" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="SEQ" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
     *       &lt;attribute name="SUBTYPE" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "atrnm",
            "atrmultirow"
    })
    public static class ATRGRP {

        @XmlElement(name = "ATR_NM")
        protected List<ATRGRPTYPE.ATRGRP.ATRNM> atrnm;
        @XmlElement(name = "ATR_MULTI_ROW")
        protected List<ATRGRPTYPE.ATRGRP.ATRMULTIROW> atrmultirow;
        @XmlAttribute(name = "id")
        protected String id;
        @XmlAttribute(name = "Label")
        protected String label;
        @XmlAttribute(name = "SEQ")
        protected Short seq;
        @XmlAttribute(name = "SUBTYPE")
        protected String subtype;

        /**
         * Gets the value of the atrnm property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the atrnm property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getATRNM().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ATRGRPTYPE.ATRGRP.ATRNM }
         *
         *
         */
        public List<ATRGRPTYPE.ATRGRP.ATRNM> getATRNM() {
            if (atrnm == null) {
                atrnm = new ArrayList<ATRGRPTYPE.ATRGRP.ATRNM>();
            }
            return this.atrnm;
        }

        /**
         * Gets the value of the atrmultirow property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the atrmultirow property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getATRMULTIROW().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ATRGRPTYPE.ATRGRP.ATRMULTIROW }
         *
         *
         */
        public List<ATRGRPTYPE.ATRGRP.ATRMULTIROW> getATRMULTIROW() {
            if (atrmultirow == null) {
                atrmultirow = new ArrayList<ATRGRPTYPE.ATRGRP.ATRMULTIROW>();
            }
            return this.atrmultirow;
        }

        /**
         * Gets the value of the id property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setId(String value) {
            this.id = value;
        }

        /**
         * Gets the value of the label property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getLabel() {
            return label;
        }

        /**
         * Sets the value of the label property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setLabel(String value) {
            this.label = value;
        }

        /**
         * Gets the value of the seq property.
         *
         * @return
         *     possible object is
         *     {@link Short }
         *
         */
        public Short getSEQ() {
            return seq;
        }

        /**
         * Sets the value of the seq property.
         *
         * @param value
         *     allowed object is
         *     {@link Short }
         *
         */
        public void setSEQ(Short value) {
            this.seq = value;
        }

        /**
         * Gets the value of the subtype property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getSUBTYPE() {
            return subtype;
        }

        /**
         * Sets the value of the subtype property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setSUBTYPE(String value) {
            this.subtype = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="ATR_NM" maxOccurs="unbounded" minOccurs="0"&gt;
         *           &lt;complexType&gt;
         *             &lt;simpleContent&gt;
         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
         *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *                 &lt;attribute name="Label" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *                 &lt;attribute name="SEQ" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
         *                 &lt;attribute name="Value" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *                 &lt;attribute name="STNDR" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *                 &lt;attribute name="REPFL" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *                 &lt;attribute name="LOVSQ" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *                 &lt;attribute name="UOM" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *               &lt;/extension&gt;
         *             &lt;/simpleContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *       &lt;/sequence&gt;
         *       &lt;attribute name="SEQ" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
         *       &lt;attribute name="ROWID" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
                "atrnm"
        })
        public static class ATRMULTIROW {

            @XmlElement(name = "ATR_NM")
            protected List<ATRGRPTYPE.ATRGRP.ATRMULTIROW.ATRNM> atrnm;
            @XmlAttribute(name = "SEQ")
            protected Short seq;
            @XmlAttribute(name = "ROWID")
            protected Integer rowid;

            /**
             * Gets the value of the atrnm property.
             *
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the atrnm property.
             *
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getATRNM().add(newItem);
             * </pre>
             *
             *
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link ATRGRPTYPE.ATRGRP.ATRMULTIROW.ATRNM }
             *
             *
             */
            public List<ATRGRPTYPE.ATRGRP.ATRMULTIROW.ATRNM> getATRNM() {
                if (atrnm == null) {
                    atrnm = new ArrayList<ATRGRPTYPE.ATRGRP.ATRMULTIROW.ATRNM>();
                }
                return this.atrnm;
            }

            /**
             * Gets the value of the seq property.
             *
             * @return
             *     possible object is
             *     {@link Short }
             *
             */
            public Short getSEQ() {
                return seq;
            }

            /**
             * Sets the value of the seq property.
             *
             * @param value
             *     allowed object is
             *     {@link Short }
             *
             */
            public void setSEQ(Short value) {
                this.seq = value;
            }

            /**
             * Gets the value of the rowid property.
             *
             * @return
             *     possible object is
             *     {@link Integer }
             *
             */
            public Integer getROWID() {
                return rowid;
            }

            /**
             * Sets the value of the rowid property.
             *
             * @param value
             *     allowed object is
             *     {@link Integer }
             *
             */
            public void setROWID(Integer value) {
                this.rowid = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             *
             * <p>The following schema fragment specifies the expected content contained within this class.
             *
             * <pre>
             * &lt;complexType&gt;
             *   &lt;simpleContent&gt;
             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
             *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *       &lt;attribute name="Label" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *       &lt;attribute name="SEQ" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
             *       &lt;attribute name="Value" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *       &lt;attribute name="STNDR" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *       &lt;attribute name="REPFL" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *       &lt;attribute name="LOVSQ" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *       &lt;attribute name="UOM" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *     &lt;/extension&gt;
             *   &lt;/simpleContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             *
             *
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                    "value"
            })
            public static class ATRNM {

                @XmlValue
                protected String value;
                @XmlAttribute(name = "id")
                protected String id;
                @XmlAttribute(name = "Label")
                protected String label;
                @XmlAttribute(name = "SEQ")
                protected Short seq;
                @XmlAttribute(name = "Value")
                protected String valueAttribute;
                @XmlAttribute(name = "STNDR")
                protected String stndr;
                @XmlAttribute(name = "REPFL")
                protected String repfl;
                @XmlAttribute(name = "LOVSQ")
                protected String lovsq;
                @XmlAttribute(name = "UOM")
                protected String uom;

                /**
                 * Gets the value of the value property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setValue(String value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the id property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public String getId() {
                    return id;
                }

                /**
                 * Sets the value of the id property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setId(String value) {
                    this.id = value;
                }

                /**
                 * Gets the value of the label property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public String getLabel() {
                    return label;
                }

                /**
                 * Sets the value of the label property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setLabel(String value) {
                    this.label = value;
                }

                /**
                 * Gets the value of the seq property.
                 *
                 * @return
                 *     possible object is
                 *     {@link Short }
                 *
                 */
                public Short getSEQ() {
                    return seq;
                }

                /**
                 * Sets the value of the seq property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link Short }
                 *
                 */
                public void setSEQ(Short value) {
                    this.seq = value;
                }

                /**
                 * Gets the value of the valueAttribute property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public String getValueAttribute() {
                    return valueAttribute;
                }

                /**
                 * Sets the value of the valueAttribute property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setValueAttribute(String value) {
                    this.valueAttribute = value;
                }

                /**
                 * Gets the value of the stndr property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public String getSTNDR() {
                    return stndr;
                }

                /**
                 * Sets the value of the stndr property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setSTNDR(String value) {
                    this.stndr = value;
                }

                /**
                 * Gets the value of the repfl property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public String getREPFL() {
                    return repfl;
                }

                /**
                 * Sets the value of the repfl property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setREPFL(String value) {
                    this.repfl = value;
                }

                /**
                 * Gets the value of the lovsq property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public String getLOVSQ() {
                    return lovsq;
                }

                /**
                 * Sets the value of the lovsq property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setLOVSQ(String value) {
                    this.lovsq = value;
                }

                /**
                 * Gets the value of the uom property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public String getUOM() {
                    return uom;
                }

                /**
                 * Sets the value of the uom property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setUOM(String value) {
                    this.uom = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;simpleContent&gt;
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
         *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *       &lt;attribute name="Label" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *       &lt;attribute name="SEQ" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
         *       &lt;attribute name="STNDR" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *       &lt;attribute name="Value" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *       &lt;attribute name="CID" type="{http://www.w3.org/2001/XMLSchema}long" /&gt;
         *       &lt;attribute name="UOM" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *       &lt;attribute name="Display_Flag" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *       &lt;attribute name="Language" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *       &lt;attribute name="Country" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *       &lt;attribute name="REPFL" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *       &lt;attribute name="LOVSQ" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *     &lt;/extension&gt;
         *   &lt;/simpleContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
                "value"
        })
        public static class ATRNM {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "id")
            protected String id;
            @XmlAttribute(name = "Label")
            protected String label;
            @XmlAttribute(name = "SEQ")
            protected Short seq;
            @XmlAttribute(name = "STNDR")
            protected String stndr;
            @XmlAttribute(name = "Value")
            protected String valueAttribute;
            @XmlAttribute(name = "CID")
            protected Long cid;
            @XmlAttribute(name = "UOM")
            protected String uom;
            @XmlAttribute(name = "Display_Flag")
            protected String displayFlag;
            @XmlAttribute(name = "Language")
            protected String language;
            @XmlAttribute(name = "Country")
            protected String country;
            @XmlAttribute(name = "REPFL")
            protected String repfl;
            @XmlAttribute(name = "LOVSQ")
            protected String lovsq;

            /**
             * Gets the value of the value property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the id property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setId(String value) {
                this.id = value;
            }

            /**
             * Gets the value of the label property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getLabel() {
                return label;
            }

            /**
             * Sets the value of the label property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setLabel(String value) {
                this.label = value;
            }

            /**
             * Gets the value of the seq property.
             *
             * @return
             *     possible object is
             *     {@link Short }
             *
             */
            public Short getSEQ() {
                return seq;
            }

            /**
             * Sets the value of the seq property.
             *
             * @param value
             *     allowed object is
             *     {@link Short }
             *
             */
            public void setSEQ(Short value) {
                this.seq = value;
            }

            /**
             * Gets the value of the stndr property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getSTNDR() {
                return stndr;
            }

            /**
             * Sets the value of the stndr property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setSTNDR(String value) {
                this.stndr = value;
            }

            /**
             * Gets the value of the valueAttribute property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getValueAttribute() {
                return valueAttribute;
            }

            /**
             * Sets the value of the valueAttribute property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setValueAttribute(String value) {
                this.valueAttribute = value;
            }

            /**
             * Gets the value of the cid property.
             *
             * @return
             *     possible object is
             *     {@link Long }
             *
             */
            public Long getCID() {
                return cid;
            }

            /**
             * Sets the value of the cid property.
             *
             * @param value
             *     allowed object is
             *     {@link Long }
             *
             */
            public void setCID(Long value) {
                this.cid = value;
            }

            /**
             * Gets the value of the uom property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getUOM() {
                return uom;
            }

            /**
             * Sets the value of the uom property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setUOM(String value) {
                this.uom = value;
            }

            /**
             * Gets the value of the displayFlag property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getDisplayFlag() {
                return displayFlag;
            }

            /**
             * Sets the value of the displayFlag property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setDisplayFlag(String value) {
                this.displayFlag = value;
            }

            /**
             * Gets the value of the language property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getLanguage() {
                return language;
            }

            /**
             * Sets the value of the language property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setLanguage(String value) {
                this.language = value;
            }

            /**
             * Gets the value of the country property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getCountry() {
                return country;
            }

            /**
             * Sets the value of the country property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setCountry(String value) {
                this.country = value;
            }

            /**
             * Gets the value of the repfl property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getREPFL() {
                return repfl;
            }

            /**
             * Sets the value of the repfl property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setREPFL(String value) {
                this.repfl = value;
            }

            /**
             * Gets the value of the lovsq property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getLOVSQ() {
                return lovsq;
            }

            /**
             * Sets the value of the lovsq property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setLOVSQ(String value) {
                this.lovsq = value;
            }

        }

    }

}