//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.19 at 02:12:16 PM IST 
//


package com.eaton.platform.integration.informatica.models.globalattributes;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ROW" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ATTR_NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ATTR_DISPLAY_NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="LAST_UPDATE_DATE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="SEQUENCE" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "row"
})
@XmlRootElement(name = "GLOBAL_ATTRIBUTE_ITM")
public class GLOBALATTRIBUTEITM {

    @XmlElement(name = "ROW")
    protected List<GLOBALATTRIBUTEITM.ROW> row;

    /**
     * Gets the value of the row property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the row property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getROW().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GLOBALATTRIBUTEITM.ROW }
     * 
     * 
     */
    public List<GLOBALATTRIBUTEITM.ROW> getROW() {
        if (row == null) {
            row = new ArrayList<GLOBALATTRIBUTEITM.ROW>();
        }
        return this.row;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ATTR_NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ATTR_DISPLAY_NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="LAST_UPDATE_DATE" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="SEQUENCE" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "attrname",
        "attrdisplayname",
        "lastupdatedate",
        "sequence"
    })
    public static class ROW {

        @XmlElement(name = "ATTR_NAME", required = true)
        protected String attrname;
        @XmlElement(name = "ATTR_DISPLAY_NAME", required = true)
        protected String attrdisplayname;
        @XmlElement(name = "LAST_UPDATE_DATE", required = true)
        protected String lastupdatedate;
        @XmlElement(name = "SEQUENCE")
        protected int sequence;

        /**
         * Gets the value of the attrname property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getATTRNAME() {
            return attrname;
        }

        /**
         * Sets the value of the attrname property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setATTRNAME(String value) {
            this.attrname = value;
        }

        /**
         * Gets the value of the attrdisplayname property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getATTRDISPLAYNAME() {
            return attrdisplayname;
        }

        /**
         * Sets the value of the attrdisplayname property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setATTRDISPLAYNAME(String value) {
            this.attrdisplayname = value;
        }

        /**
         * Gets the value of the lastupdatedate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLASTUPDATEDATE() {
            return lastupdatedate;
        }

        /**
         * Sets the value of the lastupdatedate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLASTUPDATEDATE(String value) {
            this.lastupdatedate = value;
        }

        /**
         * Gets the value of the sequence property.
         * 
         */
        public int getSEQUENCE() {
            return sequence;
        }

        /**
         * Sets the value of the sequence property.
         * 
         */
        public void setSEQUENCE(int value) {
            this.sequence = value;
        }

    }

}
