//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.05.05 at 11:36:23 AM EDT
//


package com.eaton.platform.integration.informatica.models.productfamily;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the com.eaton.platform.integration.informatica.models.productfamily package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.eaton.platform.integration.informatica.models.productfamily
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PRODUCTFAMILY }
     * @return new PRODUCTFAMILY
     */
    public PRODUCTFAMILY createPRODUCTFAMILY() {
        return new PRODUCTFAMILY();
    }

    /**
     * Create an instance of {@link PRODUCTFAMILY.ROW }
     * @return new PRODUCTFAMILY ROW
     */
    public PRODUCTFAMILY.ROW createPRODUCTFAMILYROW() {
        return new PRODUCTFAMILY.ROW();
    }

    /**
     * Create an instance of {@link PRODUCTFAMILY.ROW.ITM }
     * @return PRODUCTFAMILY ROW ITM
     */
    public PRODUCTFAMILY.ROW.ITM createPRODUCTFAMILYROWITM() {
        return new PRODUCTFAMILY.ROW.ITM();
    }

    /**
     * Create an instance of {@link PRODUCTFAMILY.ROW.ITM.ITMATRBT }
     * @return new PPRODUCTFAMILY ROW ITM ITEMATRBT
     */
    public PRODUCTFAMILY.ROW.ITM.ITMATRBT createPRODUCTFAMILYROWITMITMATRBT() {
        return new PRODUCTFAMILY.ROW.ITM.ITMATRBT();
    }

    /**
     * Create an instance of {@link PRODUCTFAMILY.ROW.ITM.ITMATRBT.ATRGRPTYPE }
     * @return PRODUCTFAMILY ROW ITM ITMATRBT ATRGRPTYPE
     */
    public PRODUCTFAMILY.ROW.ITM.ITMATRBT.ATRGRPTYPE createPRODUCTFAMILYROWITMITMATRBTATRGRPTYPE() {
        return new PRODUCTFAMILY.ROW.ITM.ITMATRBT.ATRGRPTYPE();
    }

    /**
     * Create an instance of {@link PRODUCTFAMILY.ROW.ITM.ITMATRBT.ATRGRPTYPE.ATRGRP }
     * @return PRODUCTFAMILY ROW ITM ITMATRBT ATRGRPTYPE ATRGRP
     */
    public PRODUCTFAMILY.ROW.ITM.ITMATRBT.ATRGRPTYPE.ATRGRP createPRODUCTFAMILYROWITMITMATRBTATRGRPTYPEATRGRP() {
        return new PRODUCTFAMILY.ROW.ITM.ITMATRBT.ATRGRPTYPE.ATRGRP();
    }

    /**
     * Create an instance of {@link PRODUCTFAMILY.ROW.ITM.ITMATRBT.ATRGRPTYPE.ATRGRP.ATRMULTIROW }
     * @return PRODUCTFAMILY ROW ITM ITMATRBT ATRGRPTYPE ATRGRP ATRMULTIROW
     */
    public PRODUCTFAMILY.ROW.ITM.ITMATRBT.ATRGRPTYPE.ATRGRP.ATRMULTIROW createPRODUCTFAMILYROWITMITMATRBTATRGRPTYPEATRGRPATRMULTIROW() {
        return new PRODUCTFAMILY.ROW.ITM.ITMATRBT.ATRGRPTYPE.ATRGRP.ATRMULTIROW();
    }

    /**
     * Create an instance of {@link PRODUCTFAMILY.ROW.ITM.ITMATRBT.ATRGRPTYPE.ATRGRP.ATRNM }
     * @return PRODUCTFAMILY ROW ITM ITMATRBT ATRGRPTYPE ATRGRP ATRNM
     */
    public PRODUCTFAMILY.ROW.ITM.ITMATRBT.ATRGRPTYPE.ATRGRP.ATRNM createPRODUCTFAMILYROWITMITMATRBTATRGRPTYPEATRGRPATRNM() {
        return new PRODUCTFAMILY.ROW.ITM.ITMATRBT.ATRGRPTYPE.ATRGRP.ATRNM();
    }

    /**
     * Create an instance of {@link PRODUCTFAMILY.ROW.ITM.ITMATRBT.ATRGRPTYPE.ATRGRP.ATRMULTIROW.ATRNM }
     * @return PRODUCTFAMILY ROW ITM ITMATRBT ATRGRPTYPE ATRGRP ATRMULTIROW ATRNM
     */
    public PRODUCTFAMILY.ROW.ITM.ITMATRBT.ATRGRPTYPE.ATRGRP.ATRMULTIROW.ATRNM createPRODUCTFAMILYROWITMITMATRBTATRGRPTYPEATRGRPATRMULTIROWATRNM() {
        return new PRODUCTFAMILY.ROW.ITM.ITMATRBT.ATRGRPTYPE.ATRGRP.ATRMULTIROW.ATRNM();
    }

}